# Generated by Django 4.2.2 on 2023-06-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=32)),
                ('Lastname', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
