# Generated by Django 4.2.3 on 2023-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expiry_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
