# Generated by Django 4.2.3 on 2023-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='Product',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
