# Generated by Django 4.2.3 on 2023-07-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
        ('order', '0002_orders_customer_orders_shoppingcart'),
        ('shoppingcart', '0002_shopping_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping',
            new_name='Shoppingcart',
        ),
    ]
