# Generated by Django 4.2.2 on 2023-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_status', models.CharField(max_length=32)),
                ('Item', models.CharField(max_length=32)),
                ('Customer_information', models.CharField(max_length=15)),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
