# Generated by Django 4.2.3 on 2023-07-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
        ('customer', '0001_initial'),
        ('Shoppingcart', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.delivery'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shoppingcart',
            field=models.ManyToManyField(to='Shoppingcart.shoppingcart'),
        ),
    ]
