# Generated by Django 4.2.3 on 2023-07-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_customer_orders_delivery_orders_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shoppingcart',
        ),
    ]
