# Generated by Django 4.2.3 on 2023-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_rename_product_shoppingcart_product'),
        ('order', '0002_orders_customer_orders_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shoppingcart',
        ),
        migrations.AddField(
            model_name='orders',
            name='shoppingcart',
            field=models.ManyToManyField(to='shoppingcart.shoppingcart'),
        ),
    ]
