# Generated by Django 4.2.3 on 2023-08-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
